language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - '12'
script:
  - echo "skipping tests"
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: develop
